### ISSUE TITLE
Having trouble getting the example to run

### ISSUE THREAD

**Issue by zkessin** [truqu/real-world-elm#1]
Is there any good reason to not use the elm reactor here? It would make running this much easier.

For some reason cowboy is not finding my app.js file, it may be because npm did something wrong with uglify. For a demo this feels like it just has way to many moving parts.

**Comment by ghost** [comment]
The main reason for not using elm-reactor here, is that the example is based on the code we're running in production and therefore uses the same set-up as we do. I agree that it is a bit much now, but in the blog series the example is going to be build out to a fully featured SPA.

For now see this comment: http://engineering.truqu.com/2015/08/19/real-world-elm-part-1.html#comment-2208817034

**Comment by ghost** [comment]
If your run `make elm` do you get any errors? And after running `make elm` what are the contents of the `priv/js` directory?

**Comment by zkessin** [comment]
This is the NPM debug log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'uglify' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'preuglify', 'uglify', 'postuglify' ]
6 info preuglify real-world-elm@1.1.0
7 info uglify real-world-elm@1.1.0
8 verbose unsafe-perm in lifecycle true
9 info real-world-elm@1.1.0 Failed to exec uglify script
10 verbose stack Error: real-world-elm@1.1.0 uglify: `node -e "require('grunt').tasks(['newer:uglify']);"`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid real-world-elm@1.1.0
12 verbose cwd /Users/zkessin/Documents/real-world-elm
13 error Darwin 14.5.0
14 error argv "node" "/usr/local/bin/npm" "run-script" "uglify"
15 error node v0.12.5
16 error npm  v2.11.2
17 error code ELIFECYCLE
18 error real-world-elm@1.1.0 uglify: `node -e "require('grunt').tasks(['newer:uglify']);"`
18 error Exit status 1
19 error Failed at the real-world-elm@1.1.0 uglify script 'node -e "require('grunt').tasks(['newer:uglify']);"'.
19 error This is most likely a problem with the real-world-elm package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node -e "require('grunt').tasks(['newer:uglify']);"
19 error You can get their info via:
19 error     npm owner ls real-world-elm
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by ghost** [comment]
I've created a branch [release/1.1.0](https://github.com/truqu/real-world-elm/tree/release/1.1.0) that no longer uses grunt this should fix your problems.
